/******************************************************************************
*
*       NXP(TM) and the NXP logo are trademarks of NXP
*       All other product or service names are the property of their respective owners.
*      (c) Copyright 2012 - 2016 Freescale Semiconductor Inc.
*       Copyright 2017 NXP
*       All Rights Reserved.
*
*       THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
*       BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
*       Freescale Semiconductor, Inc.
*
* Description: Memory map file
*
********************************************************************************/

#define MEMMAP_ERROR

/* Here you may define your types yourselves except following types: VAR_*, VAR_FAST_*, CONST_* and CONST_FAST_* */
/* ... */



/* Types generated by OS Sysgen: VAR_*, VAR_FAST_*, CONST_* and CONST_FAST_* */
#include "Os_memmap.h"

#ifdef MEMMAP_ERROR

#ifdef OSMEMMAP_ERROR
#error "MemMap.h, wrong pragma command"
#endif /* OSMEMMAP_ERROR */

#endif /* MEMMAP_ERROR */
